package com.plane.tracker.domain

/**
 * ICAO airport → IATA:City mapping and ICAO airline prefix → name:IATA lookup.
 * Direct port from the web app's ICAO_AIRPORTS and ICAO_AIRLINES tables.
 */
object ICAOData {

    data class AirportInfo(val iata: String, val city: String)
    data class AirlineInfo(val name: String, val iata: String)

    /** ICAO 4-letter airport code → IATA + city name */
    val airports: Map<String, AirportInfo> = mapOf(
        // UK
        "EGLL" to AirportInfo("LHR", "London"),
        "EGKK" to AirportInfo("LGW", "London Gatwick"),
        "EGSS" to AirportInfo("STN", "London Stansted"),
        "EGGW" to AirportInfo("LTN", "London Luton"),
        "EGMC" to AirportInfo("SEN", "London Southend"),
        "EGLC" to AirportInfo("LCY", "London City"),
        "EGBB" to AirportInfo("BHX", "Birmingham"),
        "EGCC" to AirportInfo("MAN", "Manchester"),
        "EGGD" to AirportInfo("BRS", "Bristol"),
        "EGNX" to AirportInfo("EMA", "East Midlands"),
        "EGPH" to AirportInfo("EDI", "Edinburgh"),
        "EGPF" to AirportInfo("GLA", "Glasgow"),
        "EGNM" to AirportInfo("LBA", "Leeds Bradford"),
        "EGGP" to AirportInfo("LPL", "Liverpool"),
        "EGHI" to AirportInfo("SOU", "Southampton"),
        "EGNT" to AirportInfo("NCL", "Newcastle"),
        "EGAA" to AirportInfo("BFS", "Belfast"),
        "EGAC" to AirportInfo("BHD", "Belfast City"),
        "EGFF" to AirportInfo("CWL", "Cardiff"),
        "EGJJ" to AirportInfo("JER", "Jersey"),
        "EGJB" to AirportInfo("GCI", "Guernsey"),
        "EGPD" to AirportInfo("ABZ", "Aberdeen"),
        // Europe
        "LFPG" to AirportInfo("CDG", "Paris"),
        "LFPO" to AirportInfo("ORY", "Paris Orly"),
        "LFMN" to AirportInfo("NCE", "Nice"),
        "LFML" to AirportInfo("MRS", "Marseille"),
        "LFLL" to AirportInfo("LYS", "Lyon"),
        "LFBD" to AirportInfo("BOD", "Bordeaux"),
        "LFBO" to AirportInfo("TLS", "Toulouse"),
        "EDDF" to AirportInfo("FRA", "Frankfurt"),
        "EDDM" to AirportInfo("MUC", "Munich"),
        "EDDB" to AirportInfo("BER", "Berlin"),
        "EDDL" to AirportInfo("DUS", "Dusseldorf"),
        "EDDH" to AirportInfo("HAM", "Hamburg"),
        "EDDK" to AirportInfo("CGN", "Cologne"),
        "EDDS" to AirportInfo("STR", "Stuttgart"),
        "EHAM" to AirportInfo("AMS", "Amsterdam"),
        "EBBR" to AirportInfo("BRU", "Brussels"),
        "EBCI" to AirportInfo("CRL", "Charleroi"),
        "LSZH" to AirportInfo("ZRH", "Zurich"),
        "LSGG" to AirportInfo("GVA", "Geneva"),
        "LOWW" to AirportInfo("VIE", "Vienna"),
        "LEMD" to AirportInfo("MAD", "Madrid"),
        "LEBL" to AirportInfo("BCN", "Barcelona"),
        "LEPA" to AirportInfo("PMI", "Palma"),
        "LEAL" to AirportInfo("ALC", "Alicante"),
        "LEMG" to AirportInfo("AGP", "Malaga"),
        "LPPT" to AirportInfo("LIS", "Lisbon"),
        "LPPR" to AirportInfo("OPO", "Porto"),
        "LIRF" to AirportInfo("FCO", "Rome"),
        "LIMC" to AirportInfo("MXP", "Milan Malpensa"),
        "LIME" to AirportInfo("BGY", "Milan Bergamo"),
        "LIPZ" to AirportInfo("VCE", "Venice"),
        "LIPE" to AirportInfo("BLQ", "Bologna"),
        "LIRN" to AirportInfo("NAP", "Naples"),
        "LGAV" to AirportInfo("ATH", "Athens"),
        "LGSR" to AirportInfo("JTR", "Santorini"),
        "LGKR" to AirportInfo("CFU", "Corfu"),
        "LTFM" to AirportInfo("IST", "Istanbul"),
        "LTAI" to AirportInfo("AYT", "Antalya"),
        "LTFJ" to AirportInfo("SAW", "Istanbul Sabiha"),
        "EKCH" to AirportInfo("CPH", "Copenhagen"),
        "ESSA" to AirportInfo("ARN", "Stockholm"),
        "ENGM" to AirportInfo("OSL", "Oslo"),
        "EFHK" to AirportInfo("HEL", "Helsinki"),
        "EPWA" to AirportInfo("WAW", "Warsaw"),
        "LKPR" to AirportInfo("PRG", "Prague"),
        "LHBP" to AirportInfo("BUD", "Budapest"),
        "LROP" to AirportInfo("OTP", "Bucharest"),
        "LRBS" to AirportInfo("BBU", "Bucharest Baneasa"),
        "LDZA" to AirportInfo("ZAG", "Zagreb"),
        "LJLJ" to AirportInfo("LJU", "Ljubljana"),
        "LYBE" to AirportInfo("BEG", "Belgrade"),
        "LWSK" to AirportInfo("SKP", "Skopje"),
        "LATI" to AirportInfo("TIA", "Tirana"),
        "EIDW" to AirportInfo("DUB", "Dublin"),
        "EICK" to AirportInfo("ORK", "Cork"),
        "EINN" to AirportInfo("SNN", "Shannon"),
        "BIKF" to AirportInfo("KEF", "Reykjavik"),
        // Middle East
        "OMDB" to AirportInfo("DXB", "Dubai"),
        "OMDW" to AirportInfo("DWC", "Dubai World Central"),
        "OMAA" to AirportInfo("AUH", "Abu Dhabi"),
        "OTHH" to AirportInfo("DOH", "Doha"),
        "OEJN" to AirportInfo("JED", "Jeddah"),
        "OERK" to AirportInfo("RUH", "Riyadh"),
        "OBBI" to AirportInfo("BAH", "Bahrain"),
        "OOMS" to AirportInfo("MCT", "Muscat"),
        "OKBK" to AirportInfo("KWI", "Kuwait"),
        "OLBA" to AirportInfo("BEY", "Beirut"),
        "OJAM" to AirportInfo("AMM", "Amman"),
        "LLBG" to AirportInfo("TLV", "Tel Aviv"),
        "OIIE" to AirportInfo("IKA", "Tehran"),
        // North America
        "KJFK" to AirportInfo("JFK", "New York"),
        "KLGA" to AirportInfo("LGA", "New York LaGuardia"),
        "KEWR" to AirportInfo("EWR", "Newark"),
        "KLAX" to AirportInfo("LAX", "Los Angeles"),
        "KORD" to AirportInfo("ORD", "Chicago"),
        "KATL" to AirportInfo("ATL", "Atlanta"),
        "KDFW" to AirportInfo("DFW", "Dallas"),
        "KDEN" to AirportInfo("DEN", "Denver"),
        "KSFO" to AirportInfo("SFO", "San Francisco"),
        "KSEA" to AirportInfo("SEA", "Seattle"),
        "KBOS" to AirportInfo("BOS", "Boston"),
        "KMIA" to AirportInfo("MIA", "Miami"),
        "KFLL" to AirportInfo("FLL", "Fort Lauderdale"),
        "KMCO" to AirportInfo("MCO", "Orlando"),
        "KIAD" to AirportInfo("IAD", "Washington"),
        "KDCA" to AirportInfo("DCA", "Washington Reagan"),
        "KPHL" to AirportInfo("PHL", "Philadelphia"),
        "KIAH" to AirportInfo("IAH", "Houston"),
        "KPHX" to AirportInfo("PHX", "Phoenix"),
        "KMSP" to AirportInfo("MSP", "Minneapolis"),
        "KDTW" to AirportInfo("DTW", "Detroit"),
        "KCLT" to AirportInfo("CLT", "Charlotte"),
        "KSLC" to AirportInfo("SLC", "Salt Lake City"),
        "KLAS" to AirportInfo("LAS", "Las Vegas"),
        "CYYZ" to AirportInfo("YYZ", "Toronto"),
        "CYUL" to AirportInfo("YUL", "Montreal"),
        "CYVR" to AirportInfo("YVR", "Vancouver"),
        "CYOW" to AirportInfo("YOW", "Ottawa"),
        "CYEG" to AirportInfo("YEG", "Edmonton"),
        "CYYC" to AirportInfo("YYC", "Calgary"),
        "MMMX" to AirportInfo("MEX", "Mexico City"),
        "MMUN" to AirportInfo("CUN", "Cancun"),
        // Asia-Pacific
        "VHHH" to AirportInfo("HKG", "Hong Kong"),
        "WSSS" to AirportInfo("SIN", "Singapore"),
        "RJTT" to AirportInfo("HND", "Tokyo Haneda"),
        "RJAA" to AirportInfo("NRT", "Tokyo Narita"),
        "RKSI" to AirportInfo("ICN", "Seoul Incheon"),
        "ZBAA" to AirportInfo("PEK", "Beijing"),
        "ZSPD" to AirportInfo("PVG", "Shanghai"),
        "RPLL" to AirportInfo("MNL", "Manila"),
        "VTBS" to AirportInfo("BKK", "Bangkok"),
        "WMKK" to AirportInfo("KUL", "Kuala Lumpur"),
        "VIDP" to AirportInfo("DEL", "Delhi"),
        "VABB" to AirportInfo("BOM", "Mumbai"),
        "VOBL" to AirportInfo("BLR", "Bangalore"),
        "YSSY" to AirportInfo("SYD", "Sydney"),
        "YMML" to AirportInfo("MEL", "Melbourne"),
        "NZAA" to AirportInfo("AKL", "Auckland"),
        // Africa
        "FAOR" to AirportInfo("JNB", "Johannesburg"),
        "FACT" to AirportInfo("CPT", "Cape Town"),
        "HECA" to AirportInfo("CAI", "Cairo"),
        "GMMN" to AirportInfo("CMN", "Casablanca"),
        "DNMM" to AirportInfo("LOS", "Lagos"),
        "HKJK" to AirportInfo("NBO", "Nairobi"),
        "HAAB" to AirportInfo("ADD", "Addis Ababa"),
        // South America
        "SBGR" to AirportInfo("GRU", "Sao Paulo"),
        "SCEL" to AirportInfo("SCL", "Santiago"),
        "SAEZ" to AirportInfo("EZE", "Buenos Aires"),
        "SKBO" to AirportInfo("BOG", "Bogota"),
        "SPJC" to AirportInfo("LIM", "Lima")
    )

    /** ICAO 3-letter airline prefix → airline name + IATA code */
    val airlines: Map<String, AirlineInfo> = mapOf(
        "BAW" to AirlineInfo("British Airways", "BA"),
        "SHT" to AirlineInfo("British Airways", "BA"),
        "EZY" to AirlineInfo("easyJet", "U2"),
        "EZS" to AirlineInfo("easyJet", "U2"),
        "RYR" to AirlineInfo("Ryanair", "FR"),
        "RUK" to AirlineInfo("Ryanair UK", "RK"),
        "WZZ" to AirlineInfo("Wizz Air", "W6"),
        "TOM" to AirlineInfo("TUI", "BY"),
        "VIR" to AirlineInfo("Virgin Atlantic", "VS"),
        "AFR" to AirlineInfo("Air France", "AF"),
        "DLH" to AirlineInfo("Lufthansa", "LH"),
        "KLM" to AirlineInfo("KLM", "KL"),
        "SWR" to AirlineInfo("Swiss", "LX"),
        "AUA" to AirlineInfo("Austrian", "OS"),
        "BEL" to AirlineInfo("Brussels Airlines", "SN"),
        "SAS" to AirlineInfo("SAS", "SK"),
        "FIN" to AirlineInfo("Finnair", "AY"),
        "TAP" to AirlineInfo("TAP Portugal", "TP"),
        "IBE" to AirlineInfo("Iberia", "IB"),
        "IBS" to AirlineInfo("Iberia Express", "I2"),
        "VLG" to AirlineInfo("Vueling", "VY"),
        "AZA" to AirlineInfo("ITA Airways", "AZ"),
        "THY" to AirlineInfo("Turkish Airlines", "TK"),
        "SXS" to AirlineInfo("SunExpress", "XQ"),
        "PGT" to AirlineInfo("Pegasus", "PC"),
        "AEE" to AirlineInfo("Aegean", "A3"),
        "LOT" to AirlineInfo("LOT Polish", "LO"),
        "CSA" to AirlineInfo("Czech Airlines", "OK"),
        "ROT" to AirlineInfo("TAROM", "RO"),
        "WIF" to AirlineInfo("Wideroe", "WF"),
        "ICE" to AirlineInfo("Icelandair", "FI"),
        "EIN" to AirlineInfo("Aer Lingus", "EI"),
        "NRS" to AirlineInfo("Norwegian", "D8"),
        "NAX" to AirlineInfo("Norwegian", "DY"),
        "UAE" to AirlineInfo("Emirates", "EK"),
        "ETD" to AirlineInfo("Etihad", "EY"),
        "QTR" to AirlineInfo("Qatar Airways", "QR"),
        "SVA" to AirlineInfo("Saudia", "SV"),
        "GIA" to AirlineInfo("Garuda Indonesia", "GA"),
        "RBA" to AirlineInfo("Royal Brunei", "BI"),
        "GFA" to AirlineInfo("Gulf Air", "GF"),
        "KAC" to AirlineInfo("Kuwait Airways", "KU"),
        "MEA" to AirlineInfo("MEA", "ME"),
        "RJA" to AirlineInfo("Royal Jordanian", "RJ"),
        "ELY" to AirlineInfo("El Al", "LY"),
        "AAL" to AirlineInfo("American Airlines", "AA"),
        "DAL" to AirlineInfo("Delta", "DL"),
        "UAL" to AirlineInfo("United Airlines", "UA"),
        "SWA" to AirlineInfo("Southwest", "WN"),
        "JBU" to AirlineInfo("JetBlue", "B6"),
        "NKS" to AirlineInfo("Spirit", "NK"),
        "FFT" to AirlineInfo("Frontier", "F9"),
        "ASA" to AirlineInfo("Alaska Airlines", "AS"),
        "HAL" to AirlineInfo("Hawaiian Airlines", "HA"),
        "ACA" to AirlineInfo("Air Canada", "AC"),
        "WJA" to AirlineInfo("WestJet", "WS"),
        "AMX" to AirlineInfo("Aeromexico", "AM"),
        "CPA" to AirlineInfo("Cathay Pacific", "CX"),
        "SIA" to AirlineInfo("Singapore Airlines", "SQ"),
        "ANA" to AirlineInfo("ANA", "NH"),
        "JAL" to AirlineInfo("Japan Airlines", "JL"),
        "KAL" to AirlineInfo("Korean Air", "KE"),
        "AAR" to AirlineInfo("Asiana", "OZ"),
        "CCA" to AirlineInfo("Air China", "CA"),
        "CES" to AirlineInfo("China Eastern", "MU"),
        "CSN" to AirlineInfo("China Southern", "CZ"),
        "THA" to AirlineInfo("Thai Airways", "TG"),
        "MAS" to AirlineInfo("Malaysia Airlines", "MH"),
        "PAL" to AirlineInfo("Philippine Airlines", "PR"),
        "VNA" to AirlineInfo("Vietnam Airlines", "VN"),
        "EVA" to AirlineInfo("EVA Air", "BR"),
        "AIC" to AirlineInfo("Air India", "AI"),
        "IGO" to AirlineInfo("IndiGo", "6E"),
        "QFA" to AirlineInfo("Qantas", "QF"),
        "ANZ" to AirlineInfo("Air New Zealand", "NZ"),
        "ETH" to AirlineInfo("Ethiopian", "ET"),
        "SAA" to AirlineInfo("South African", "SA"),
        "RAM" to AirlineInfo("Royal Air Maroc", "AT"),
        "MSR" to AirlineInfo("EgyptAir", "MS"),
        "KQA" to AirlineInfo("Kenya Airways", "KQ"),
        "TAM" to AirlineInfo("LATAM", "LA"),
        "GLO" to AirlineInfo("GOL", "G3"),
        "AVA" to AirlineInfo("Avianca", "AV"),
        "CMP" to AirlineInfo("Copa Airlines", "CM"),
        "FDB" to AirlineInfo("flydubai", "FZ"),
        "AXB" to AirlineInfo("Air India Express", "IX"),
        "EWG" to AirlineInfo("Eurowings", "EW"),
        "BER" to AirlineInfo("Norse Atlantic", "Z0"),
        "LOG" to AirlineInfo("Loganair", "LM"),
        "BEE" to AirlineInfo("Flybe", "BE"),
        "CFE" to AirlineInfo("BA CityFlyer", "CJ"),
        "TCX" to AirlineInfo("Thomas Cook", "MT"),
        "MON" to AirlineInfo("Monarch", "ZB"),
        "JTL" to AirlineInfo("Jet2", "LS")
    )

    /** Normalise route airports: if 4-char ICAO, convert to IATA + fill city */
    fun normaliseAirport(code: String, cityHint: String?): Pair<String, String> {
        if (code.length == 4) {
            val info = airports[code]
            if (info != null) return info.iata to info.city
        }
        return code to (cityHint ?: "")
    }

    /** Look up airline from callsign's 3-letter ICAO prefix */
    fun airlineFromCallsign(callsign: String): AirlineInfo? {
        val prefix = callsign.uppercase().replace(Regex("[0-9]"), "").take(3)
        return airlines[prefix]
    }
}
